// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBancario.Infraestrutura.Dados;

#nullable disable

namespace SistemaBancario.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoBancario))]
    [Migration("20250812220452_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaBancario.Dominio.Entidades.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("VARCHAR(6)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_Conta_Numero");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("SistemaBancario.Dominio.Entidades.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("CodigoTransacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("DataHoraTransacao")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("IdContaDestino")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("IdContaOrigem")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTransacao")
                        .IsUnique()
                        .HasDatabaseName("IX_Transacao_Codigo");

                    b.HasIndex("IdContaDestino");

                    b.HasIndex("IdContaOrigem");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("SistemaBancario.Dominio.Entidades.Transacao", b =>
                {
                    b.HasOne("SistemaBancario.Dominio.Entidades.Conta", "ContaDestino")
                        .WithMany("TransacoesDestino")
                        .HasForeignKey("IdContaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaBancario.Dominio.Entidades.Conta", "ContaOrigem")
                        .WithMany("TransacoesOrigem")
                        .HasForeignKey("IdContaOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("SistemaBancario.Dominio.Entidades.Conta", b =>
                {
                    b.Navigation("TransacoesDestino");

                    b.Navigation("TransacoesOrigem");
                });
#pragma warning restore 612, 618
        }
    }
}
