name: CI

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
      BACKEND_IMAGE: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/backend
      FRONTEND_IMAGE: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore SistemaBancario.sln

      - name: Build
        run: dotnet build SistemaBancario.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test SistemaBancario.sln --configuration Release --no-build --logger trx

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"
          if-no-files-found: ignore

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login "${{ env.ACR_LOGIN_SERVER }}" -u "${{ secrets.AZURE_ACR_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: |
          docker build --file Dockerfile --tag "${{ env.BACKEND_IMAGE }}:${{ github.sha }}" .
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker tag "${{ env.BACKEND_IMAGE }}:${{ github.sha }}" "${{ env.BACKEND_IMAGE }}:latest"
          fi

      - name: Build frontend Docker image
        run: |
          docker build --file frontend/Dockerfile --tag "${{ env.FRONTEND_IMAGE }}:${{ github.sha }}" frontend
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker tag "${{ env.FRONTEND_IMAGE }}:${{ github.sha }}" "${{ env.FRONTEND_IMAGE }}:latest"
          fi

      - name: Push backend Docker image
        run: |
          docker push "${{ env.BACKEND_IMAGE }}:${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker push "${{ env.BACKEND_IMAGE }}:latest"
          fi

      - name: Push frontend Docker image
        run: |
          docker push "${{ env.FRONTEND_IMAGE }}:${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker push "${{ env.FRONTEND_IMAGE }}:latest"
          fi
